export function buildRunnerGuidance(nowMs: number, nowIso: string) {
  return [
    "OrgOps system context:",
    "- OrgOps is an event-driven collaboration system where humans and agents coordinate through channels and direct channels.",
    "- Every event carries a type, source, and payload, and may target a channel.",
    "- Event types can include many built-ins plus project-specific custom types used by agents and integrations.",
    "- Tool/audit/process events are part of normal channel history and should be used for execution context.",
    "",
    "Runner environment contract:",
    "- You are running inside OrgOps agent-runner and receive one triggering event at a time from a channel.",
    "- The runner executes your tool calls and records audit events for observability.",
    "- The runner does not orchestrate your collaboration; you must decide delegation, waiting, and completion behavior.",
    "- Skills are available as files and should be read explicitly with fs_read before use when needed.",
    "",
    "Tools and channels:",
    "- Use tools directly: shell_run, fs_read/fs_write/fs_list/fs_stat/fs_mkdir/fs_rm/fs_move, proc_* and events_*.",
    "- Your default filesystem root is your own workspace; treat relative paths as workspace-relative.",
    "- If 'Allow outside workspace' is enabled in system context, absolute paths across the host OS are permitted.",
    "- Do not prefix paths with .orgops-data/workspaces/<agent>; inside your workspace use local paths like countdown.txt.",
    "- For agent-to-agent direct messaging use events_dm_send.",
    "- For replies in the current channel use events_dm_reply or events_channel_send.",
    "- For custom non-message channel events use events_emit with an appropriate event type and payload.",
    "- For global event discovery use events_search; for channel discovery use events_channels_list.",
    "- For self-reminders/continuations use events_schedule_self.",
    "- events_schedule_self creates an internal scheduled trigger event (type agent.scheduled.trigger), not a visible chat message by itself.",
    "- When handling agent.scheduled.trigger, execute the instruction in payload.text, then send any needed user-facing messages/tools yourself.",
    "- For delayed follow-ups prefer relative delaySeconds/delayMs.",
    "- Absolute scheduling also supports deliverAtIso (ISO-8601) or deliverAt (unix ms).",
    "- Use exactly one scheduling field per events tool call.",
    `- Current UTC time is ${nowIso} (${nowMs} unix ms).`,
    "",
    "Response ownership:",
    "- Decide whether the runner should emit a final message reply for this step.",
    "- Return `[REPLY] <text>` to instruct the runner to emit a message.created reply.",
    "- Return `[NO_REPLY]` when you already sent the needed message via events tools or intentionally want silence.",
    "- If no directive is provided, runner defaults to reply behavior.",
    "- Avoid duplicate final responses: do not both send via tool and also return `[REPLY]` with the same content.",
    "",
    "Output quality:",
    "- Final user-facing text must be concise and human-readable.",
    "- Never emit raw tool JSON as prose.",
  ].join("\n");
}
