import {
  chmodSync,
  copyFileSync,
  cpSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import * as tar from "tar";
import { build } from "esbuild";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OPSCLI_ROOT = resolve(__dirname, "..");
const REPO_ROOT = resolve(OPSCLI_ROOT, "..", "..");
const TMP_ROOT = resolve(OPSCLI_ROOT, ".release-tmp");
const OUTPUT_DIR = resolve(REPO_ROOT, "dist");
const SNAPSHOT_DIR = resolve(TMP_ROOT, "snapshot");
const ASSET_DIR = resolve(SNAPSHOT_DIR, "assets");
const ORGOPS_BUNDLE_NAME = "orgops-bundle.tar.gz";
const DOCS_BUNDLE_NAME = "orgops-system-docs.md";
const BUILD_INFO_NAME = "opscli-build-info.json";
const SEA_CONFIG_NAME = "sea-config.json";
const SEA_BLOB_NAME = "opscli-sea-prep.blob";
const SEA_FUSE = "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2";

function runCommand(command: string, args: string[]) {
  const result = spawnSync(command, args, {
    cwd: REPO_ROOT,
    stdio: "inherit",
    shell: process.platform === "win32",
  });
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} failed with status ${result.status}`);
  }
}

function outputNameForCurrentPlatform() {
  if (process.platform === "darwin") return "opscli-macos";
  if (process.platform === "win32") return "opscli-windows.exe";
  return "opscli-linux";
}

function stageOrgOpsSource() {
  const stagedRoot = resolve(TMP_ROOT, "orgops");
  rmSync(stagedRoot, { recursive: true, force: true });
  mkdirSync(stagedRoot, { recursive: true });
  const includePaths = [
    "apps/api",
    "apps/agent-runner",
    "apps/ui",
    "packages",
    "docs",
    "skills",
    "README.md",
    "package.json",
    "package-lock.json",
    "tsconfig.base.json",
  ];
  for (const includePath of includePaths) {
    cpSync(resolve(REPO_ROOT, includePath), resolve(stagedRoot, includePath), {
      recursive: true,
    });
  }
  return stagedRoot;
}

function buildDocsBundle() {
  const readme = readFileSync(resolve(REPO_ROOT, "README.md"), "utf-8");
  const spec = readFileSync(resolve(REPO_ROOT, "docs/SPEC.md"), "utf-8");
  const runnerReadme = readFileSync(
    resolve(REPO_ROOT, "apps/agent-runner/README.md"),
    "utf-8"
  );
  return [
    "# OrgOps Bundled Docs",
    "",
    "Use this as authoritative docs while guiding setup and operations.",
    "",
    "## README",
    readme,
    "",
    "## SPEC",
    spec,
    "",
    "## Agent Runner README",
    runnerReadme,
  ].join("\n");
}

async function buildReleaseExecutable() {
  rmSync(TMP_ROOT, { recursive: true, force: true });
  mkdirSync(ASSET_DIR, { recursive: true });
  mkdirSync(OUTPUT_DIR, { recursive: true });

  stageOrgOpsSource();
  await tar.c(
    {
      gzip: true,
      cwd: TMP_ROOT,
      file: resolve(ASSET_DIR, ORGOPS_BUNDLE_NAME),
    },
    ["orgops"]
  );
  writeFileSync(resolve(ASSET_DIR, DOCS_BUNDLE_NAME), buildDocsBundle(), "utf-8");
  writeFileSync(
    resolve(ASSET_DIR, BUILD_INFO_NAME),
    JSON.stringify(
      {
        builtAt: new Date().toISOString(),
        target: `${process.platform}-${process.arch}`,
        runtime: process.version,
      },
      null,
      2
    ),
    "utf-8"
  );

  const entryFile = resolve(OPSCLI_ROOT, "src/index.ts");
  const bundledEntryFile = resolve(SNAPSHOT_DIR, "opscli.cjs");
  await build({
    entryPoints: [entryFile],
    platform: "node",
    target: "node22",
    format: "cjs",
    bundle: true,
    outfile: bundledEntryFile,
    banner: {
      js: "// generated by opscli build-release",
    },
  });

  const seaBlobPath = resolve(TMP_ROOT, SEA_BLOB_NAME);
  const seaConfigPath = resolve(TMP_ROOT, SEA_CONFIG_NAME);
  writeFileSync(
    seaConfigPath,
    JSON.stringify(
      {
        main: bundledEntryFile,
        output: seaBlobPath,
        disableExperimentalSEAWarning: true,
        useSnapshot: false,
        useCodeCache: false,
        assets: {
          [ORGOPS_BUNDLE_NAME]: resolve(ASSET_DIR, ORGOPS_BUNDLE_NAME),
          [DOCS_BUNDLE_NAME]: resolve(ASSET_DIR, DOCS_BUNDLE_NAME),
          [BUILD_INFO_NAME]: resolve(ASSET_DIR, BUILD_INFO_NAME),
        },
      },
      null,
      2
    ),
    "utf-8"
  );

  runCommand("node", ["--experimental-sea-config", seaConfigPath]);

  const outputPath = resolve(OUTPUT_DIR, outputNameForCurrentPlatform());
  copyFileSync(process.execPath, outputPath);

  if (process.platform !== "win32") {
    chmodSync(outputPath, 0o755);
  }

  if (process.platform === "darwin") {
    runCommand("codesign", ["--remove-signature", outputPath]);
  }

  const postjectArgs = [
    outputPath,
    "NODE_SEA_BLOB",
    seaBlobPath,
    "--sentinel-fuse",
    SEA_FUSE,
  ];
  if (process.platform === "darwin") {
    postjectArgs.push("--macho-segment-name", "NODE_SEA");
  }
  runCommand("npx", ["postject", ...postjectArgs]);

  if (process.platform === "darwin") {
    runCommand("codesign", ["--sign", "-", outputPath]);
  }

  if (process.platform !== "win32") {
    chmodSync(outputPath, 0o755);
  }

  console.log(`Built SEA executable: ${outputPath}`);
}

void buildReleaseExecutable();
