import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import * as tar from "tar";
import { build } from "esbuild";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OPSCLI_ROOT = resolve(__dirname, "..");
const REPO_ROOT = resolve(OPSCLI_ROOT, "..", "..");
const TMP_ROOT = resolve(OPSCLI_ROOT, ".release-tmp");
const OUTPUT_DIR = resolve(REPO_ROOT, "dist");
const SNAPSHOT_DIR = resolve(TMP_ROOT, "snapshot");
const ASSET_DIR = resolve(SNAPSHOT_DIR, "assets");
const ORGOPS_BUNDLE_NAME = "orgops-bundle.tar.gz";
const DOCS_BUNDLE_NAME = "orgops-system-docs.md";
const BUILD_INFO_NAME = "opscli-build-info.json";

function runCommand(command: string, args: string[]) {
  const result = spawnSync(command, args, {
    cwd: REPO_ROOT,
    stdio: "inherit",
    shell: process.platform === "win32",
  });
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} failed with status ${result.status}`);
  }
}

function targetForCurrentPlatform() {
  if (process.platform === "darwin") return "node18-macos-x64";
  if (process.platform === "win32") return "node18-win-x64";
  return "node18-linux-x64";
}

function outputNameForTarget(target: string) {
  const suffix = target
    .replace(/^node\d+-/, "")
    .replace("-x64", "")
    .replace("-arm64", "-arm64");
  return process.platform === "win32" ? `opscli-${suffix}.exe` : `opscli-${suffix}`;
}

function stageOrgOpsSource() {
  const stagedRoot = resolve(TMP_ROOT, "orgops");
  rmSync(stagedRoot, { recursive: true, force: true });
  mkdirSync(stagedRoot, { recursive: true });
  const includePaths = [
    "apps/api",
    "apps/agent-runner",
    "apps/ui",
    "packages",
    "docs",
    "skills",
    "README.md",
    "package.json",
    "package-lock.json",
    "tsconfig.base.json",
  ];
  for (const includePath of includePaths) {
    cpSync(resolve(REPO_ROOT, includePath), resolve(stagedRoot, includePath), {
      recursive: true,
    });
  }
  return stagedRoot;
}

function buildDocsBundle() {
  const readme = readFileSync(resolve(REPO_ROOT, "README.md"), "utf-8");
  const spec = readFileSync(resolve(REPO_ROOT, "docs/SPEC.md"), "utf-8");
  const runnerReadme = readFileSync(
    resolve(REPO_ROOT, "apps/agent-runner/README.md"),
    "utf-8"
  );
  return [
    "# OrgOps Bundled Docs",
    "",
    "Use this as authoritative docs while guiding setup and operations.",
    "",
    "## README",
    readme,
    "",
    "## SPEC",
    spec,
    "",
    "## Agent Runner README",
    runnerReadme,
  ].join("\n");
}

async function buildReleaseExecutable() {
  rmSync(TMP_ROOT, { recursive: true, force: true });
  mkdirSync(ASSET_DIR, { recursive: true });
  mkdirSync(OUTPUT_DIR, { recursive: true });

  const stagedRoot = stageOrgOpsSource();
  await tar.c(
    {
      gzip: true,
      cwd: TMP_ROOT,
      file: resolve(ASSET_DIR, ORGOPS_BUNDLE_NAME),
    },
    ["orgops"]
  );
  writeFileSync(resolve(ASSET_DIR, DOCS_BUNDLE_NAME), buildDocsBundle(), "utf-8");
  writeFileSync(
    resolve(ASSET_DIR, BUILD_INFO_NAME),
    JSON.stringify(
      {
        builtAt: new Date().toISOString(),
        target: process.env.ORGOPS_OPSCLI_PKG_TARGET || targetForCurrentPlatform(),
      },
      null,
      2
    ),
    "utf-8"
  );

  const entryFile = resolve(OPSCLI_ROOT, "src/index.ts");
  const bundledEntryFile = resolve(SNAPSHOT_DIR, "opscli.cjs");
  await build({
    entryPoints: [entryFile],
    platform: "node",
    target: "node18",
    format: "cjs",
    bundle: true,
    outfile: bundledEntryFile,
    banner: {
      js: "// generated by opscli build-release",
    },
  });

  const pkgManifestPath = resolve(SNAPSHOT_DIR, "package.json");
  writeFileSync(
    pkgManifestPath,
    JSON.stringify(
      {
        name: "orgops-opscli-bundle",
        private: true,
        version: "0.0.1",
        bin: "opscli.cjs",
        pkg: {
          assets: ["assets/**/*"],
        },
      },
      null,
      2
    ),
    "utf-8"
  );

  const requestedTarget = process.env.ORGOPS_OPSCLI_PKG_TARGET || targetForCurrentPlatform();
  const outputPath = resolve(OUTPUT_DIR, outputNameForTarget(requestedTarget));
  runCommand("npx", [
    "pkg",
    "--compress",
    "Brotli",
    "--target",
    requestedTarget,
    "--output",
    outputPath,
    pkgManifestPath,
  ]);
  console.log(`Built: ${outputPath}`);
}

void buildReleaseExecutable();
