import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  DEFAULT_ANTHROPIC_MODEL_ID,
  DEFAULT_OPENAI_MODEL_ID,
  DEFAULT_OPENROUTER_MODEL_ID,
  ROOT_ENV_FILE,
} from "./config";
import type { ModelProvider } from "./types";
import { writeRoleMessage } from "./ui";

export function parseSimpleEnv(raw: string): Record<string, string> {
  const result: Record<string, string> = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const equalsIdx = trimmed.indexOf("=");
    if (equalsIdx <= 0) continue;
    const key = trimmed.slice(0, equalsIdx).trim();
    const value = trimmed.slice(equalsIdx + 1).trim();
    const unquoted =
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
        ? value.slice(1, -1)
        : value;
    result[key] = unquoted;
  }
  return result;
}

export function loadDotEnvIntoProcess(envPath: string) {
  if (!existsSync(envPath)) return;
  const parsed = parseSimpleEnv(readFileSync(envPath, "utf-8"));
  for (const [key, value] of Object.entries(parsed)) {
    if (!process.env[key]) process.env[key] = value;
  }
}

export function writeMergedEnvFile(envPath: string, patch: Record<string, string>) {
  const existing = existsSync(envPath)
    ? parseSimpleEnv(readFileSync(envPath, "utf-8"))
    : {};
  const next: Record<string, string> = { ...existing, ...patch };
  const lines = [
    "# Generated by OrgOps OpsCLI",
    ...Object.entries(next).map(([key, value]) => `${key}=${value}`),
  ];
  writeFileSync(envPath, `${lines.join("\n")}\n`, "utf-8");
}

export function getOpsCliEnvPath() {
  return join(process.cwd(), ROOT_ENV_FILE);
}

export function getModelId() {
  const configured = process.env.ORGOPS_OPSCLI_MODEL?.trim();
  return configured || DEFAULT_OPENAI_MODEL_ID;
}

export function normalizeProvider(provider: string): ModelProvider | null {
  const normalized = provider.trim().toLowerCase();
  if (normalized === "openai") return "openai";
  if (normalized === "anthropic" || normalized === "claude") return "anthropic";
  if (normalized === "openrouter" || normalized === "or") return "openrouter";
  return null;
}

export function getModelProvider(modelId: string): ModelProvider {
  const [provider] = modelId.split(":");
  return normalizeProvider(provider ?? "") ?? "openai";
}

function getProviderLabel(provider: ModelProvider) {
  if (provider === "openai") return "OpenAI";
  if (provider === "anthropic") return "Claude (Anthropic)";
  return "OpenRouter";
}

function getProviderApiKeyEnvKey(provider: ModelProvider) {
  if (provider === "openai") return "OPENAI_API_KEY";
  if (provider === "anthropic") return "ANTHROPIC_API_KEY";
  return "OPENROUTER_API_KEY";
}

function getDefaultModelIdForProvider(provider: ModelProvider) {
  if (provider === "openai") return DEFAULT_OPENAI_MODEL_ID;
  if (provider === "anthropic") return DEFAULT_ANTHROPIC_MODEL_ID;
  return DEFAULT_OPENROUTER_MODEL_ID;
}

function getAlternateProviders(provider: ModelProvider): ModelProvider[] {
  return (["openai", "anthropic", "openrouter"] as const).filter((x) => x !== provider);
}

async function askProviderChoice(ask: (prompt: string) => Promise<string>): Promise<ModelProvider> {
  while (true) {
    const answer = (
      await ask(
        "No model API key found. Choose provider: [1] OpenAI, [2] Claude (Anthropic), [3] OpenRouter: "
      )
    )
      .trim()
      .toLowerCase();
    if (answer === "1" || answer === "openai") return "openai";
    if (answer === "2" || answer === "claude" || answer === "anthropic") return "anthropic";
    if (answer === "3" || answer === "openrouter" || answer === "or") return "openrouter";
    writeRoleMessage("opscli", "Please choose 1, 2, or 3.");
  }
}

export async function ensureModelCredentials(input: {
  ask: (prompt: string) => Promise<string>;
  rootEnvPath: string;
}) {
  const { ask, rootEnvPath } = input;
  let modelId = getModelId();
  let provider = getModelProvider(modelId);
  const hasOpenAiKey = Boolean(process.env.OPENAI_API_KEY?.trim());
  const hasAnthropicKey = Boolean(process.env.ANTHROPIC_API_KEY?.trim());
  const hasOpenRouterKey = Boolean(process.env.OPENROUTER_API_KEY?.trim());
  const hasAnyKey = hasOpenAiKey || hasAnthropicKey || hasOpenRouterKey;

  if (!hasAnyKey) {
    provider = await askProviderChoice(ask);
    modelId = getDefaultModelIdForProvider(provider);
    process.env.ORGOPS_OPSCLI_MODEL = modelId;
    writeMergedEnvFile(rootEnvPath, { ORGOPS_OPSCLI_MODEL: modelId });
    writeRoleMessage("opscli", `Using model: ${modelId}`);
  }

  let requiredApiKeyEnv = getProviderApiKeyEnvKey(provider);
  if (!process.env[requiredApiKeyEnv]?.trim()) {
    const alternate = getAlternateProviders(provider).find((candidate) =>
      Boolean(process.env[getProviderApiKeyEnvKey(candidate)]?.trim())
    );
    if (alternate) {
      const answer = (
        await ask(
          `Current model uses ${getProviderLabel(provider)} but ${requiredApiKeyEnv} is missing.\nSwitch to ${getProviderLabel(alternate)} model? [Y/n]: `
        )
      )
        .trim()
        .toLowerCase();
      if (!answer || answer === "y" || answer === "yes") {
        provider = alternate;
        modelId = getDefaultModelIdForProvider(provider);
        process.env.ORGOPS_OPSCLI_MODEL = modelId;
        writeMergedEnvFile(rootEnvPath, { ORGOPS_OPSCLI_MODEL: modelId });
        writeRoleMessage("opscli", `Using model: ${modelId}`);
        requiredApiKeyEnv = getProviderApiKeyEnvKey(provider);
      }
    }
  }

  if (!process.env[requiredApiKeyEnv]?.trim()) {
    const answer = (await ask(`${requiredApiKeyEnv} not found. Enter key: `)).trim();
    if (!answer) return false;
    process.env[requiredApiKeyEnv] = answer;
    writeMergedEnvFile(rootEnvPath, { [requiredApiKeyEnv]: answer });
    writeRoleMessage("opscli", `Saved ${requiredApiKeyEnv} to ${rootEnvPath}`);
  }
  return true;
}
