import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join, resolve } from "node:path";
import { spawn } from "node:child_process";
import { hostname } from "node:os";
import { PassThrough } from "node:stream";
import * as repl from "node:repl";
import { inspect } from "node:util";
import { randomBytes } from "node:crypto";
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";
import * as tar from "tar";
import { generate, type LlmMessage } from "@orgops/llm";

type ShellResult = {
  exitCode: number | null;
  timedOut: boolean;
  stdout: string;
  stderr: string;
  durationMs: number;
};

type SessionRunHooks = {
  appendObservation: (type: string, payload: Record<string, unknown>) => void;
  requestUserInput: (promptText: string) => Promise<string>;
};

type RlmSession = {
  replServer: repl.REPLServer;
  context: Record<string, unknown>;
  reservedKeys: Set<string>;
  exited: boolean;
  exitCode: number;
  runHooks: SessionRunHooks | null;
};

type SessionMemory = {
  summary: string;
  history: LlmMessage[];
};

const MODEL_ID = process.env.ORGOPS_OPSCLI_MODEL ?? "openai:gpt-4o-mini";
const MAX_STEPS = Number(process.env.ORGOPS_OPSCLI_MAX_STEPS ?? 20);
const COMMAND_TIMEOUT_MS = Number(process.env.ORGOPS_OPSCLI_COMMAND_TIMEOUT_MS ?? 120_000);
const EVAL_TIMEOUT_MS = Number(process.env.ORGOPS_OPSCLI_EVAL_TIMEOUT_MS ?? 30_000);
const MAX_OUTPUT_CHARS = 12_000;
const MAX_INPUT_CHARS = 12_000;
const MAX_CONTEXT_CHARS = Number(process.env.ORGOPS_OPSCLI_MAX_CONTEXT_CHARS ?? 100_000);
const MAX_SUMMARY_CHARS = Number(process.env.ORGOPS_OPSCLI_MAX_SUMMARY_CHARS ?? 14_000);
const SUMMARY_CHUNK_MESSAGES = Number(process.env.ORGOPS_OPSCLI_SUMMARY_CHUNK_MESSAGES ?? 8);
const MIN_RECENT_MESSAGES = Number(process.env.ORGOPS_OPSCLI_MIN_RECENT_MESSAGES ?? 12);
const MAX_SYSTEM_DOC_CHARS = Number(
  process.env.ORGOPS_OPSCLI_MAX_SYSTEM_DOC_CHARS ?? 40_000
);
const BUNDLED_ROOT_DIR_NAME = "orgops";
const ROOT_ENV_FILE = ".env";
const DEFAULT_API_URL = "http://localhost:8787";
const DEFAULT_RUNNER_TOKEN = "dev-runner-token";
const RUNTIME_DIR = (() => {
  try {
    return __dirname;
  } catch {
    return process.cwd();
  }
})();

function ensureScaffoldedDataDir() {
  const dataDir = join(process.cwd(), ".orgops-data");
  mkdirSync(dataDir, { recursive: true });
  return dataDir;
}

function parseSimpleEnv(raw: string): Record<string, string> {
  const result: Record<string, string> = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const equalsIdx = trimmed.indexOf("=");
    if (equalsIdx <= 0) continue;
    const key = trimmed.slice(0, equalsIdx).trim();
    const value = trimmed.slice(equalsIdx + 1).trim();
    const unquoted =
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
        ? value.slice(1, -1)
        : value;
    result[key] = unquoted;
  }
  return result;
}

function loadDotEnvIntoProcess(envPath: string) {
  if (!existsSync(envPath)) return;
  const parsed = parseSimpleEnv(readFileSync(envPath, "utf-8"));
  for (const [key, value] of Object.entries(parsed)) {
    if (!process.env[key]) process.env[key] = value;
  }
}

function writeMergedEnvFile(envPath: string, patch: Record<string, string>) {
  const existing = existsSync(envPath)
    ? parseSimpleEnv(readFileSync(envPath, "utf-8"))
    : {};
  const next: Record<string, string> = { ...existing, ...patch };
  const lines = [
    "# Generated by OrgOps OpsCLI",
    ...Object.entries(next).map(([key, value]) => `${key}=${value}`),
  ];
  writeFileSync(envPath, `${lines.join("\n")}\n`, "utf-8");
}

function getRuntimeAssetPath(fileName: string) {
  const candidates = [
    join(RUNTIME_DIR, "assets", fileName),
    resolve(process.cwd(), "apps/opscli/assets", fileName),
  ];
  return candidates.find((candidate) => existsSync(candidate)) ?? candidates[0]!;
}

function loadBundledDocsText() {
  const docsPath = getRuntimeAssetPath("orgops-system-docs.md");
  if (!existsSync(docsPath)) return "";
  const docs = readFileSync(docsPath, "utf-8").trim();
  if (!docs) return "";
  return truncateText(docs, MAX_SYSTEM_DOC_CHARS).text;
}

function getBundledArchivePath() {
  return getRuntimeAssetPath("orgops-bundle.tar.gz");
}

async function extractBundledOrgOps(options?: {
  targetDir?: string;
  force?: boolean;
}) {
  const archivePath = getBundledArchivePath();
  if (!existsSync(archivePath)) {
    throw new Error(
      "Bundled OrgOps archive not found. Use a release-built opscli binary."
    );
  }
  const targetDir = resolve(options?.targetDir ?? process.cwd());
  mkdirSync(targetDir, { recursive: true });
  const extractedRoot = join(targetDir, BUNDLED_ROOT_DIR_NAME);
  const shouldExtract = options?.force || !existsSync(extractedRoot);
  if (shouldExtract) {
    await tar.x({ file: archivePath, cwd: targetDir });
  }
  return extractedRoot;
}

type SetupComponent = "api" | "runner" | "ui";

function sanitizeSetupComponents(raw?: string[]) {
  const normalized = new Set<SetupComponent>();
  for (const entry of raw ?? []) {
    const value = entry.trim().toLowerCase();
    if (value === "api" || value === "runner" || value === "ui") {
      normalized.add(value);
    }
  }
  return normalized.size > 0
    ? Array.from(normalized)
    : (["api", "runner", "ui"] as SetupComponent[]);
}

function resolveWorkspaceForComponent(component: SetupComponent) {
  if (component === "api") return "@orgops/api";
  if (component === "runner") return "@orgops/agent-runner";
  return "@orgops/ui";
}

function buildSuggestedRunCommands(components: SetupComponent[]) {
  const commands: string[] = [];
  for (const component of components) {
    if (component === "api") {
      commands.push("npm run --workspace @orgops/api start");
    } else if (component === "runner") {
      commands.push("npm run --workspace @orgops/agent-runner start");
    } else if (component === "ui") {
      commands.push("npm run --workspace @orgops/ui preview");
    }
  }
  return commands;
}

async function setupBundledOrgOps(options?: {
  targetDir?: string;
  components?: string[];
  forceExtract?: boolean;
  installDependencies?: boolean;
  buildUi?: boolean;
}) {
  const extractedRoot = await extractBundledOrgOps({
    targetDir: options?.targetDir,
    force: options?.forceExtract,
  });
  const components = sanitizeSetupComponents(options?.components);
  const installDependencies = options?.installDependencies !== false;
  const buildUi = options?.buildUi !== false;
  const envPath = join(extractedRoot, ROOT_ENV_FILE);
  const existingEnv = existsSync(envPath)
    ? parseSimpleEnv(readFileSync(envPath, "utf-8"))
    : {};
  const openAiApiKey = process.env.OPENAI_API_KEY?.trim();
  writeMergedEnvFile(envPath, {
    OPENAI_API_KEY: openAiApiKey || existingEnv.OPENAI_API_KEY || "",
    ORGOPS_MASTER_KEY:
      existingEnv.ORGOPS_MASTER_KEY || randomBytes(32).toString("base64"),
    ORGOPS_RUNNER_TOKEN:
      existingEnv.ORGOPS_RUNNER_TOKEN ||
      process.env.ORGOPS_RUNNER_TOKEN ||
      DEFAULT_RUNNER_TOKEN,
    ORGOPS_API_URL:
      existingEnv.ORGOPS_API_URL || process.env.ORGOPS_API_URL || DEFAULT_API_URL,
  });

  const steps: Array<Record<string, unknown>> = [];
  if (installDependencies) {
    const installResult = await runShell(
      `cd "${extractedRoot}" && npm ci`,
      30 * 60_000
    );
    steps.push({
      step: "npm ci",
      exitCode: installResult.exitCode,
      timedOut: installResult.timedOut,
      durationMs: installResult.durationMs,
      stderr: truncateText(installResult.stderr, 4000).text,
      stdout: truncateText(installResult.stdout, 4000).text,
    });
    if (installResult.exitCode !== 0 || installResult.timedOut) {
      return {
        ok: false,
        extractedRoot,
        components,
        steps,
        message: "Dependency install failed.",
      };
    }
  }

  for (const component of components) {
    const workspace = resolveWorkspaceForComponent(component);
    if (component !== "ui" || !buildUi) {
      steps.push({
        step: `prepared ${workspace}`,
        exitCode: 0,
        timedOut: false,
        durationMs: 0,
      });
      continue;
    }
    const command = `cd "${extractedRoot}" && npm run --workspace ${workspace} build`;
    const result = await runShell(command, 10 * 60_000);
    steps.push({
      step: command,
      exitCode: result.exitCode,
      timedOut: result.timedOut,
      durationMs: result.durationMs,
      stderr: truncateText(result.stderr, 4000).text,
      stdout: truncateText(result.stdout, 4000).text,
    });
    if (result.exitCode !== 0 || result.timedOut) {
      return {
        ok: false,
        extractedRoot,
        components,
        steps,
        message: `Setup failed while preparing ${component}.`,
      };
    }
  }

  return {
    ok: true,
    extractedRoot,
    components,
    envPath,
    suggestedRunCommands: buildSuggestedRunCommands(components),
    steps,
  };
}

function extractCode(input: string): string {
  const text = input.trim();
  if (!text) return "";
  const fenced = text.match(
    /```(?:repl|js|javascript|ts|typescript)?\s*([\s\S]*?)\s*```/i
  );
  return fenced?.[1] ? fenced[1].trim() : text;
}

function truncateText(value: string, maxChars: number) {
  if (value.length <= maxChars) return { text: value, truncated: false };
  return {
    text: `${value.slice(0, maxChars)}\n...[truncated ${value.length - maxChars} chars]`,
    truncated: true,
  };
}

function formatValue(value: unknown): string {
  try {
    return inspect(value, {
      depth: 4,
      maxArrayLength: 100,
      maxStringLength: 8_000,
      breakLength: 120,
      compact: false,
    });
  } catch {
    return String(value);
  }
}

function estimateMessageChars(messages: LlmMessage[]) {
  return messages.reduce((acc, message) => acc + message.content.length, 0);
}

function summarizeMessages(messages: LlmMessage[]) {
  return messages
    .map((message, index) => {
      const oneLine = message.content.replace(/\s+/g, " ").trim();
      const clipped = truncateText(oneLine, 240).text.replace(/\n/g, " ");
      return `${index + 1}. ${message.role}: ${clipped}`;
    })
    .join("\n");
}

function appendToSummary(previousSummary: string, addition: string) {
  const merged = previousSummary ? `${previousSummary}\n${addition}` : addition;
  if (merged.length <= MAX_SUMMARY_CHARS) return merged;
  return merged.slice(merged.length - MAX_SUMMARY_CHARS);
}

function enforceMemoryBudget(memory: SessionMemory) {
  while (
    estimateMessageChars(memory.history) + memory.summary.length > MAX_CONTEXT_CHARS &&
    memory.history.length > MIN_RECENT_MESSAGES
  ) {
    const removableCount = Math.max(
      1,
      Math.min(SUMMARY_CHUNK_MESSAGES, memory.history.length - MIN_RECENT_MESSAGES)
    );
    const removed = memory.history.splice(0, removableCount);
    memory.summary = appendToSummary(memory.summary, summarizeMessages(removed));
  }
}

function appendHistoryMessage(memory: SessionMemory, message: LlmMessage) {
  const clipped = truncateText(message.content, MAX_OUTPUT_CHARS);
  memory.history.push({ role: message.role, content: clipped.text });
  enforceMemoryBudget(memory);
}

async function runShell(command: string, timeoutMs: number): Promise<ShellResult> {
  const startedAt = Date.now();
  return new Promise((resolve) => {
    const child = spawn(command, {
      cwd: process.cwd(),
      env: process.env,
      shell: true,
    });
    let out = "";
    let err = "";
    let timedOut = false;
    const timer = setTimeout(() => {
      timedOut = true;
      child.kill("SIGTERM");
      setTimeout(() => child.kill("SIGKILL"), 500).unref();
    }, timeoutMs);
    child.stdout.on("data", (chunk) => {
      out += String(chunk);
      if (out.length > MAX_OUTPUT_CHARS) out = out.slice(-MAX_OUTPUT_CHARS);
    });
    child.stderr.on("data", (chunk) => {
      err += String(chunk);
      if (err.length > MAX_OUTPUT_CHARS) err = err.slice(-MAX_OUTPUT_CHARS);
    });
    child.on("close", (exitCode) => {
      clearTimeout(timer);
      resolve({
        exitCode,
        timedOut,
        stdout: out,
        stderr: err,
        durationMs: Date.now() - startedAt,
      });
    });
  });
}

function buildSystemPrompt() {
  const docsText = loadBundledDocsText();
  const sections = [
    "You are OrgOps OpsCLI, a recursive maintenance REPL agent for this host.",
    "You are controlling a self-contained OrgOps release bundle.",
    "Read and use global `prompt` before acting.",
    "Return exactly ONE JavaScript REPL snippet each turn.",
    "Do NOT return JSON and do NOT wrap in markdown fences.",
    "Use shell(command) to execute host commands.",
    "Use print(...args) to write output to stdout.",
    "Use input(question) to ask the user for stdin input.",
    "Use exit(code) to finish and request process termination.",
    "Use extractOrgOps(options?) to extract bundled OrgOps source to disk.",
    "Use setupOrgOps(options?) to extract + install deps + configure selected components.",
    "Use getBundledDocs() when you need OrgOps architecture/deployment details.",
    "State can be persisted across turns using global variables.",
    "If prompt is empty, ask for goal using input(question).",
  ];
  if (docsText) {
    sections.push(`Bundled OrgOps docs (truncated):\n${docsText}`);
  }
  return sections.join("\n");
}

function createSession(): RlmSession {
  const inputStream = new PassThrough();
  const outputStream = new PassThrough();
  const replServer = repl.start({
    prompt: "",
    terminal: false,
    input: inputStream,
    output: outputStream,
    useGlobal: false,
    ignoreUndefined: false,
    useColors: false,
  });
  const context = replServer.context as Record<string, unknown>;
  Object.assign(context, {
    console,
    process,
    Buffer,
    setTimeout,
    clearTimeout,
    setInterval,
    clearInterval,
    fetch,
  });
  const session: RlmSession = {
    replServer,
    context,
    reservedKeys: new Set(Object.keys(context)),
    exited: false,
    exitCode: 0,
    runHooks: null,
  };
  const appendObservation = (type: string, payload: Record<string, unknown>) => {
    session.runHooks?.appendObservation(type, payload);
  };
  Object.assign(context, {
    shell: async (command: string) => runShell(command, COMMAND_TIMEOUT_MS),
    print: (...args: unknown[]) => {
      const text = args.map((arg) => formatValue(arg)).join(" ");
      console.log(`\nopscli> ${text}`);
      appendObservation("opscli.repl.print", { text });
      return text;
    },
    input: async (question?: string) => {
      const promptText =
        typeof question === "string" && question.trim()
          ? question.trim()
          : "Please provide input";
      const answer = await session.runHooks?.requestUserInput(promptText);
      const value = answer ?? "";
      appendObservation("opscli.stdin.input", {
        question: promptText,
        answer: value,
      });
      return value;
    },
    exit: (code?: number) => {
      const normalizedCode =
        typeof code === "number" && Number.isFinite(code) ? Math.floor(code) : 0;
      session.exited = true;
      session.exitCode = normalizedCode;
      appendObservation("opscli.repl.exit", { code: normalizedCode });
      return normalizedCode;
    },
    clear: () => {
      const ctx = session.context;
      for (const key of Object.keys(ctx)) {
        if (session.reservedKeys.has(key)) continue;
        delete ctx[key];
      }
      return "Context cleared.";
    },
    help: () =>
      "Use prompt, shell(command), print(...args), input(question), exit(code), clear(), extractOrgOps(options?), setupOrgOps(options?), getBundledDocs(), and global state.",
    getBundledDocs: () => loadBundledDocsText(),
    extractOrgOps: async (options?: { targetDir?: string; force?: boolean }) =>
      extractBundledOrgOps(options),
    setupOrgOps: async (options?: {
      targetDir?: string;
      components?: string[];
      forceExtract?: boolean;
      installDependencies?: boolean;
      buildUi?: boolean;
    }) => setupBundledOrgOps(options),
  });
  session.reservedKeys.add("prompt");
  session.reservedKeys.add("shell");
  session.reservedKeys.add("print");
  session.reservedKeys.add("input");
  session.reservedKeys.add("exit");
  session.reservedKeys.add("clear");
  session.reservedKeys.add("help");
  session.reservedKeys.add("getBundledDocs");
  session.reservedKeys.add("extractOrgOps");
  session.reservedKeys.add("setupOrgOps");
  return session;
}

function withTimeout<T>(promise: Promise<T>, timeoutMs: number): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    const timer = setTimeout(() => {
      reject(new Error(`Operation timed out after ${timeoutMs}ms`));
    }, timeoutMs);
    promise.then(
      (value) => {
        clearTimeout(timer);
        resolve(value);
      },
      (error) => {
        clearTimeout(timer);
        reject(error);
      }
    );
  });
}

async function evaluateInput(session: RlmSession, code: string): Promise<string> {
  const scriptValue = await new Promise<unknown>((resolve, reject) => {
    session.replServer.eval(code, session.context as any, "opscli-repl", (error, result) => {
      if (error) {
        reject(error);
        return;
      }
      resolve(result);
    });
  });
  const value =
    scriptValue && typeof (scriptValue as Promise<unknown>).then === "function"
      ? await withTimeout(scriptValue as Promise<unknown>, EVAL_TIMEOUT_MS)
      : scriptValue;
  return truncateText(formatValue(value), MAX_OUTPUT_CHARS).text;
}

async function runAutonomousTask(
  goal: string,
  session: RlmSession,
  requestUserInput: (promptText: string) => Promise<string>
): Promise<{ requestedExit: boolean; exitCode: number }> {
  session.exited = false;
  session.exitCode = 0;
  session.context.prompt = goal;
  const memory: SessionMemory = { summary: "", history: [] };
  appendHistoryMessage(memory, {
    role: "user",
    content: JSON.stringify(
      {
        type: "opscli.prompt",
        text: truncateText(goal, MAX_INPUT_CHARS).text,
        isEmpty: goal.trim().length === 0,
        host: {
          platform: process.platform,
          arch: process.arch,
          hostname: hostname(),
          cwd: process.cwd(),
        },
        promptReplPath: "globalThis.prompt",
      },
      null,
      2
    ),
  });

  session.runHooks = {
    appendObservation: (type, payload) => {
      appendHistoryMessage(memory, {
        role: "user",
        content: JSON.stringify({ type, ...payload }, null, 2),
      });
    },
    requestUserInput,
  };

  for (let step = 1; step <= MAX_STEPS; step += 1) {
    const modelMessages: LlmMessage[] = [{ role: "system", content: buildSystemPrompt() }];
    if (memory.summary.trim()) {
      modelMessages.push({
        role: "system",
        content: `Session rolling summary:\n${memory.summary}`,
      });
    }
    modelMessages.push(...memory.history);
    modelMessages.push({
      role: "user",
      content: JSON.stringify(
        {
          type: "opscli.repl.next_input.requested",
          step,
          promptAvailableInRepl: true,
          promptReplPath: "globalThis.prompt",
        },
        null,
        2
      ),
    });

    const result = await generate(MODEL_ID, modelMessages, { maxSteps: 1 });
    const modelText = result.text ?? "";
    const code = extractCode(modelText);
    if (!code.trim()) {
      appendHistoryMessage(memory, { role: "assistant", content: modelText });
      appendHistoryMessage(memory, {
        role: "user",
        content: "Your last reply was empty. Return one non-empty JavaScript REPL snippet.",
      });
      continue;
    }

    const truncatedInput = truncateText(code, MAX_INPUT_CHARS);
    console.log(`\nopscli[js:${step}] ${truncatedInput.text}`);
    appendHistoryMessage(memory, { role: "assistant", content: code });

    try {
      const outputText = await evaluateInput(session, code);
      console.log(`result:\n${outputText}`);
      appendHistoryMessage(memory, {
        role: "user",
        content: JSON.stringify(
          {
            type: "opscli.repl.output",
            step,
            output: outputText,
          },
          null,
          2
        ),
      });
    } catch (error) {
      const outputText = truncateText(String(error), MAX_OUTPUT_CHARS).text;
      console.log(`error:\n${outputText}`);
      appendHistoryMessage(memory, {
        role: "user",
        content: JSON.stringify(
          {
            type: "opscli.repl.error",
            step,
            error: outputText,
          },
          null,
          2
        ),
      });
    }

    if (session.exited) {
      console.log(`\nopscli> agent requested exit(${session.exitCode}).\n`);
      session.runHooks = null;
      return { requestedExit: true, exitCode: session.exitCode };
    }
  }

  session.runHooks = null;
  console.log(`\nopscli> Stopped after ${MAX_STEPS} steps without exit(code).\n`);
  return { requestedExit: false, exitCode: 0 };
}

async function main() {
  const dataDir = ensureScaffoldedDataDir();
  const rootEnvPath = join(process.cwd(), ROOT_ENV_FILE);
  loadDotEnvIntoProcess(rootEnvPath);
  console.log(`OrgOps OpsCLI ready.`);
  console.log(`Scaffolded data dir: ${dataDir}`);
  const rl = createInterface({ input: stdin, output: stdout });
  if (!process.env.OPENAI_API_KEY?.trim()) {
    const answer = (await rl.question("OPENAI_API_KEY not found. Enter key: ")).trim();
    if (!answer) {
      console.error("OPENAI_API_KEY is required.");
      rl.close();
      process.exitCode = 1;
      return;
    }
    process.env.OPENAI_API_KEY = answer;
    writeMergedEnvFile(rootEnvPath, { OPENAI_API_KEY: answer });
    console.log(`Saved OPENAI_API_KEY to ${rootEnvPath}`);
  }
  const session = createSession();
  console.log("Type a maintenance goal (can be empty), or 'exit' to quit.");
  try {
    while (true) {
      const input = await rl.question("\nYou> ");
      const normalized = input.trim().toLowerCase();
      if (normalized === "exit" || normalized === "quit") break;
      const result = await runAutonomousTask(input, session, async (promptText) => {
        return rl.question(`\nAgent asks> ${promptText}\nYou> `);
      });
      if (result.requestedExit) {
        process.exitCode = result.exitCode;
        break;
      }
    }
  } finally {
    session.runHooks = null;
    session.replServer.close();
    rl.close();
  }
}

void main();
