import type { AuthSnapshot } from "../auth-session";
import type { ApiActivationResult, ApiExecutionApprovalCommand, ApiExecutionActivationCommand, ApiExecutionDeactivationCommand, ActivationPlan, ActivationPlanCommand, GrantView, ReleaseView, Result, RolloutView, SnapshotView, SourceLibraryApi as SourceLibraryApiContract, SourceView, SyncAttemptView } from "./api";

export type ApiExecutionConfirmation = { action: "APPROVE" | "ACTIVATE" | "DEACTIVATE"; releaseId: string; digest: string; acknowledged: true };
export type CredentialDraft = { username: string; password: string };
export type SourceDetailTab = "OVERVIEW" | "COMPATIBILITY" | "CONTENTS" | "SECURITY" | "ACTIVITY";
export type ContextError = { target: string; code: string; message: string };
export type SourceLibraryState = { phase: "idle" | "loading" | "ready" | "error" | "forbidden"; busy: boolean; principalGeneration: number; sources: SourceView[]; releases: ReleaseView[]; selectedSourceId: string | null; selectedReleaseId: string | null; selectedSource: SourceView | null; selectedRelease: ReleaseView | null; detailTab: SourceDetailTab; addDrawerOpen: boolean; contextErrors: ContextError[]; attempts: SyncAttemptView[]; snapshots: SnapshotView[]; grants: GrantView[]; humans: { id: string; username?: string; displayName?: string }[]; rolloutPlan: ActivationPlan | null; rollout: RolloutView | null; credentialDraft: CredentialDraft; writesBlocked: boolean; lastGoodSnapshot: SnapshotView | null; lastGoodReleases: ReleaseView[]; message: string | null; error: { code: string; message: string } | null };
export type SourceLibraryApi = SourceLibraryApiContract;
export type SourceLibraryActions = ReturnType<typeof createSourceLibraryController>;
export type SourceLibraryControllerDeps = { api: SourceLibraryApi; expectedUserId: string; refreshAuth: () => Promise<AuthSnapshot | null>; invalidateAuthority: () => void; flushSensitiveUpdate?: (notify: () => void) => void };

const initial = (): SourceLibraryState => ({ phase: "idle", busy: false, principalGeneration: 0, sources: [], releases: [], selectedSourceId: null, selectedReleaseId: null, selectedSource: null, selectedRelease: null, detailTab: "OVERVIEW", addDrawerOpen: false, contextErrors: [], attempts: [], snapshots: [], grants: [], humans: [], rolloutPlan: null, rollout: null, credentialDraft: { username: "", password: "" }, writesBlocked: false, lastGoodSnapshot: null, lastGoodReleases: [], message: null, error: null });
const conflict = (message = "Source Library changed; reload before writing.") => ({ code: "REVISION_CONFLICT", message });

export function createSourceLibraryController(deps: SourceLibraryControllerDeps) {
  let state = initial(); let closed = false; let principalGeneration = 0; let operationGeneration = 0; let currentAbort: AbortController | null = null; const listeners = new Set<() => void>();
  const publish = (patch: Partial<SourceLibraryState>) => { if (closed) return; state = { ...state, ...patch, principalGeneration }; listeners.forEach(listener => listener()); };
  const validTabs: readonly SourceDetailTab[] = ["OVERVIEW", "COMPATIBILITY", "CONTENTS", "SECURITY", "ACTIVITY"];
  const setUrl = (patch: { source?: string | null; release?: string | null; tab?: SourceDetailTab | null }, mode: "replace" | "push" = "replace") => {
    if (typeof window === "undefined") return;
    const url = new URL(window.location.href);
    for (const [key, value] of [["source", patch.source], ["release", patch.release], ["tab", patch.tab]] as const) {
      if (value === undefined) continue;
      if (value === null || value === "") url.searchParams.delete(key); else url.searchParams.set(key, value);
    }
    window.history[mode === "push" ? "pushState" : "replaceState"]({}, "", url);
  };
  function addContextError(target: string, error: { code: string; message: string }) {
    const next = { target, code: error.code, message: error.message };
    if (state.contextErrors.some(item => item.target === next.target && item.code === next.code)) return;
    publish({ contextErrors: [...state.contextErrors, next] });
  }
  const syncAttemptFrom = (value: unknown): SyncAttemptView | null => {
    if (!value || typeof value !== "object") return null;
    const attempt = (value as Record<string, unknown>).syncAttempt;
    return attempt && typeof attempt === "object" ? attempt as SyncAttemptView : null;
  };
  const syncFailureFrom = (attempt: SyncAttemptView | null) => attempt && attempt.state !== "SUCCEEDED" && attempt.state !== "RUNNING" ? { code: attempt.failureCode ?? "SYNC_FAILED", message: "Synchronization failed; last-good content is unchanged." } : null;
  const sourceIdFromResult = (value: unknown) => { if (value && typeof value === "object") { const source = (value as Record<string, unknown>).source; if (source && typeof source === "object" && typeof (source as Record<string, unknown>).sourceId === "string") return (source as { sourceId: string }).sourceId; } return state.selectedSource?.sourceId ?? null; };
  const detailOperation = () => { supersede(); const generation = operationGeneration; const abort = new AbortController(); currentAbort = abort; return { generation, principal: principalGeneration, abort }; };
  const supersede = () => { operationGeneration += 1; currentAbort?.abort(); currentAbort = null; };
  const begin = () => { supersede(); const generation = operationGeneration; const abort = new AbortController(); currentAbort = abort; publish({ busy: true, phase: state.phase === "idle" ? "loading" : state.phase, error: null }); return { generation, principal: principalGeneration, abort }; };
  const owned = (generation: number, principal: number) => !closed && generation === operationGeneration && principal === principalGeneration;
  const clearCredential = () => publish({ credentialDraft: { username: "", password: "" } });
  async function authorize(principal: number) { if (principal !== principalGeneration || closed) return false; let auth: AuthSnapshot | null; try { auth = await deps.refreshAuth(); } catch { auth = null; } if (!auth && !closed && principal === principalGeneration) { try { auth = await deps.refreshAuth(); } catch { auth = null; } } if (closed || principal !== principalGeneration) return false; if (!auth || !auth.authenticated || !auth.isAdmin || auth.mustChangePassword || auth.userId !== deps.expectedUserId) { principalGeneration += 1; supersede(); publish({ phase: "forbidden", busy: false, selectedSource: null, selectedRelease: null, selectedSourceId: null, selectedReleaseId: null, attempts: [], snapshots: [], grants: [], credentialDraft: { username: "", password: "" }, error: { code: "FORBIDDEN", message: "Administrator access is required." } }); deps.invalidateAuthority(); return false; } return true; }
  function finish(generation: number, principal: number) { if (owned(generation, principal)) publish({ busy: false }); }
  function projectMutation(value: unknown) { if (!value || typeof value !== "object") return; const candidate = value as Record<string, unknown>; const sourceValue = candidate.source && typeof candidate.source === "object" ? candidate.source : candidate; if (sourceValue && typeof sourceValue === "object" && typeof (sourceValue as Record<string, unknown>).sourceId === "string" && typeof (sourceValue as Record<string, unknown>).revision === "number") { const next = sourceValue as SourceView; publish({ sources: state.sources.some(item => item.sourceId === next.sourceId) ? state.sources.map(item => item.sourceId === next.sourceId ? next : item) : [...state.sources, next], selectedSource: state.selectedSource?.sourceId === next.sourceId ? next : state.selectedSource }); } const releaseValue = candidate.release; if (releaseValue && typeof releaseValue === "object" && typeof (releaseValue as Record<string, unknown>).packageReleaseId === "string") { const next = releaseValue as ReleaseView; publish({ releases: state.releases.map(item => item.packageReleaseId === next.packageReleaseId ? next : item), selectedRelease: state.selectedRelease?.packageReleaseId === next.packageReleaseId ? next : state.selectedRelease, lastGoodReleases: state.lastGoodReleases.map(item => item.packageReleaseId === next.packageReleaseId ? next : item) }); } }
  async function load() { if (closed) return; const op = begin(); if (!await authorize(op.principal)) return; const [sources, releases] = await Promise.all([deps.api.listSources(op.abort.signal), deps.api.listReleases(op.abort.signal)]); if (!owned(op.generation, op.principal)) return; if (!sources.ok || !releases.ok) { const error = !sources.ok ? sources.error : !releases.ok ? releases.error : { code: "PROTOCOL", message: "Source Library response could not be confirmed." }; publish({ phase: "error", busy: false, error, message: error.message }); return; } const humans = typeof deps.api.listHumans === "function" ? await deps.api.listHumans(op.abort.signal).catch(() => ({ ok: false as const, error: { code: "NETWORK", message: "Human list unavailable." } })) : { ok: false as const, error: { code: "NETWORK", message: "Human list unavailable." } }; if (!owned(op.generation, op.principal)) return; publish({ phase: "ready", busy: false, sources: sources.value, releases: releases.value, selectedSource: null, selectedRelease: null, selectedSourceId: null, selectedReleaseId: null, attempts: [], snapshots: [], grants: [], writesBlocked: false, message: null, error: null, lastGoodReleases: releases.value }); await restoreUrlSelection(); }
  async function restoreUrlSelection() {
    if (closed || typeof window === "undefined") return;
    const op = detailOperation();
    const params = new URL(window.location.href).searchParams;
    const sourceId = params.get("source");
    const releaseId = params.get("release");
    const rawTab = params.get("tab");
    const tab = validTabs.includes(rawTab as SourceDetailTab) ? rawTab as SourceDetailTab : "OVERVIEW";
    const requestedSource = sourceId ? state.sources.find(item => item.sourceId === sourceId) ?? null : null;
    const requestedRelease = releaseId ? state.releases.find(item => item.packageReleaseId === releaseId) ?? null : null;
    const releaseSource = requestedRelease ? state.sources.find(item => item.sourceId === requestedRelease.authoritySourceId || item.sourceId === requestedRelease.contentSourceId) ?? null : null;
    const selectedSource = requestedSource ?? releaseSource;
    const releaseBelongsToSource = !requestedRelease || sourceId === null || (typeof requestedRelease.authoritySourceId !== "string" && typeof requestedRelease.contentSourceId !== "string") || requestedRelease.authoritySourceId === sourceId || requestedRelease.contentSourceId === sourceId;
    const invalid = (sourceId !== null && !requestedSource) || (releaseId !== null && (!requestedRelease || !selectedSource || !releaseBelongsToSource));
    if (invalid) {
      setUrl({ source: null, release: null, tab: null });
      if (owned(op.generation, op.principal)) publish({ busy: false, selectedSourceId: null, selectedReleaseId: null, selectedSource: null, selectedRelease: null, attempts: [], snapshots: [], grants: [], lastGoodSnapshot: null, lastGoodReleases: [], contextErrors: [], error: { code: "NOT_FOUND", message: "The requested Source Library selection is unavailable." }, message: "The requested Source Library selection is unavailable." });
      return;
    }
    setUrl({ source: selectedSource?.sourceId ?? null, release: requestedRelease?.packageReleaseId ?? null, tab: rawTab && validTabs.includes(rawTab as SourceDetailTab) ? tab : rawTab ? null : undefined });
    publish({ busy: true, selectedSourceId: selectedSource?.sourceId ?? null, selectedReleaseId: requestedRelease?.packageReleaseId ?? null, selectedSource, selectedRelease: requestedRelease, detailTab: tab, attempts: [], snapshots: [], grants: [], error: null, message: null });
    if (selectedSource) {
      const [attempts, snapshots] = await Promise.all([deps.api.listAttempts(selectedSource.sourceId, op.abort.signal), deps.api.listSnapshots(selectedSource.sourceId, op.abort.signal)]);
      if (owned(op.generation, op.principal)) publish({ busy: false, attempts: attempts.ok ? attempts.value : [], snapshots: snapshots.ok ? snapshots.value : [], lastGoodSnapshot: snapshots.ok && snapshots.value.length ? snapshots.value[0] : state.lastGoodSnapshot });
    } else if (owned(op.generation, op.principal)) publish({ busy: false });
  }
  async function selectSource(id: string) { if (closed || state.writesBlocked) return; const tabAtStart = state.detailTab; const op = begin(); if (!await authorize(op.principal)) return; publish({ selectedSourceId: null, selectedReleaseId: null, selectedSource: null, selectedRelease: null, attempts: [], snapshots: [], grants: [], lastGoodSnapshot: null }); const result = await deps.api.getSource(id, op.abort.signal); if (!owned(op.generation, op.principal)) return; if (!result.ok) { setUrl({ source: null, release: null, tab: null }); publish({ busy: false, contextErrors: [], error: { code: "NOT_FOUND", message: "The requested Source Library selection is unavailable." }, message: "The requested Source Library selection is unavailable." }); return; } const [attempts, snapshots] = await Promise.all([deps.api.listAttempts(id, op.abort.signal), deps.api.listSnapshots(id, op.abort.signal)]); if (!owned(op.generation, op.principal)) return; const detailTab = state.detailTab === tabAtStart ? "OVERVIEW" : state.detailTab; setUrl({ source: result.value.sourceId, release: null, tab: detailTab }, "push"); publish({ busy: false, selectedSourceId: result.value.sourceId, selectedSource: result.value, selectedReleaseId: null, selectedRelease: null, detailTab, attempts: attempts.ok ? attempts.value : [], snapshots: snapshots.ok ? snapshots.value : [], lastGoodSnapshot: snapshots.ok && snapshots.value.length ? snapshots.value[0] : state.lastGoodSnapshot, error: null, message: null }); }
  async function selectRelease(id: string) { if (closed || state.writesBlocked) return; const op = begin(); if (!await authorize(op.principal)) return; publish({ selectedSourceId: null, selectedReleaseId: null, selectedSource: null, selectedRelease: null, attempts: [], snapshots: [], grants: [], lastGoodSnapshot: null, lastGoodReleases: [] }); const result = await deps.api.getRelease(id, op.abort.signal); if (!owned(op.generation, op.principal)) return; if (!result.ok) { setUrl({ source: null, release: null, tab: null }); publish({ busy: false, contextErrors: [], error: { code: "NOT_FOUND", message: "The requested Source Library selection is unavailable." }, message: "The requested Source Library selection is unavailable." }); return; } const grants = await deps.api.listGrants(id, op.abort.signal); if (!owned(op.generation, op.principal)) return; const source = state.sources.find(item => item.sourceId === result.value.authoritySourceId || item.sourceId === result.value.contentSourceId) ?? null; setUrl({ source: source?.sourceId ?? null, release: result.value.packageReleaseId, tab: "OVERVIEW" }, "push"); publish({ busy: false, selectedReleaseId: result.value.packageReleaseId, selectedRelease: result.value, selectedSourceId: source?.sourceId ?? null, selectedSource: source, detailTab: "OVERVIEW", grants: grants.ok ? grants.value : [], lastGoodReleases: [result.value], error: null, message: null }); }
  function selectTab(tab: SourceDetailTab) { if (!validTabs.includes(tab)) return; setUrl({ tab }, "push"); publish({ detailTab: tab }); }
  async function mutate<T>(operation: (signal: AbortSignal) => Promise<Result<T>>, options: { sync?: boolean } = {}) { clearCredential(); if (closed || (state.writesBlocked && !options.sync)) return; const op = begin(); if (!await authorize(op.principal)) return; const result = await operation(op.abort.signal); if (!owned(op.generation, op.principal)) return; const liveAuth = await deps.refreshAuth().catch(() => null); if (!owned(op.generation, op.principal) || !liveAuth || !liveAuth.authenticated || !liveAuth.isAdmin || liveAuth.mustChangePassword || liveAuth.userId !== deps.expectedUserId) { if (owned(op.generation, op.principal)) { principalGeneration += 1; supersede(); publish({ phase: "forbidden", busy: false, selectedSource: null, selectedRelease: null, selectedSourceId: null, selectedReleaseId: null, credentialDraft: { username: "", password: "" }, error: { code: "FORBIDDEN", message: "Administrator access is required." } }); deps.invalidateAuthority(); } return; } if (!result.ok) { const blocked = result.error.code === "REVISION_CONFLICT" || result.error.code === "STATE_CONFLICT" || options.sync; publish({ busy: false, ...(options.sync ? { lastGoodSnapshot: state.lastGoodSnapshot } : {}), writesBlocked: blocked ?? false, error: result.error, message: result.error.message }); return; } const attempt = syncAttemptFrom(result.value); const failure = syncFailureFrom(attempt); projectMutation(result.value); if (failure) { const sourceId = sourceIdFromResult(result.value) ?? "unknown"; publish({ busy: false, writesBlocked: true, error: failure, message: failure.message, attempts: attempt ? [...state.attempts.filter(item => item.attemptId !== attempt.attemptId), attempt] : state.attempts }); addContextError(sourceId, failure); return result.value; } if (attempt?.state === "SUCCEEDED") { const sourceId = sourceIdFromResult(result.value); publish({ busy: false, writesBlocked: false, message: null, error: null, contextErrors: sourceId ? state.contextErrors.filter(item => item.target !== sourceId) : state.contextErrors, attempts: [...state.attempts.filter(item => item.attemptId !== attempt.attemptId), attempt] }); return result.value; } publish({ busy: false, message: null, error: null }); return result.value; }
  async function createSource(input: Record<string, unknown>) { const value = await mutate(signal => deps.api.createSource(input, signal)); if (value && typeof value === "object") { const candidate = value as { source?: SourceView; syncAttempt?: SyncAttemptView }; if (candidate.source?.sourceId) { setUrl({ source: candidate.source.sourceId, release: null, tab: "OVERVIEW" }, "push"); publish({ addDrawerOpen: false, selectedSourceId: candidate.source.sourceId, selectedSource: candidate.source, selectedReleaseId: null, selectedRelease: null, detailTab: "OVERVIEW", attempts: candidate.syncAttempt ? [...state.attempts.filter(item => item.attemptId !== candidate.syncAttempt!.attemptId), candidate.syncAttempt] : state.attempts }); } } return value; }
  async function patchSource(sourceId: string, input: Record<string, unknown>) { return mutate(signal => deps.api.patchSource(sourceId, input, signal)); }
  async function removeSource(sourceId: string, expectedRevision: number) { return mutate(signal => deps.api.removeSource(sourceId, { expectedRevision }, signal)); }
  async function restoreSource(sourceId: string, expectedRevision: number) { return mutate(signal => deps.api.restoreSource(sourceId, { expectedRevision }, signal)); }
  async function deleteCredential(sourceId: string, expectedRevision: number) { clearCredential(); return mutate(signal => deps.api.deleteReadCredential(sourceId, { expectedRevision }, signal)); }
  async function sync(sourceId = state.selectedSource?.sourceId) { if (!sourceId) return; const source = state.sources.find(item => item.sourceId === sourceId) ?? state.selectedSource; if (!source) return; const value = await mutate(signal => deps.api.syncSource(sourceId, { expectedRevision: source.revision }, signal), { sync: true }); const attempt = syncAttemptFrom(value); if (attempt) { publish({ attempts: [...state.attempts.filter(item => item.attemptId !== attempt.attemptId), attempt] }); if (attempt.state === "SUCCEEDED" && state.selectedSourceId === sourceId) { const snapshots = await deps.api.listSnapshots(sourceId); if (state.selectedSourceId === sourceId && snapshots.ok) publish({ snapshots: snapshots.value, lastGoodSnapshot: snapshots.value[0] ?? state.lastGoodSnapshot }); } } else if (state.error) { addContextError(sourceId, state.error); } }
  async function approve(releaseId = state.selectedRelease?.packageReleaseId, action: "approve" | "reject" | "withdraw" | "reopen" = "approve") { const release = state.selectedRelease; if (!releaseId || !release) return; const value = await mutate(signal => deps.api.reviewRelease(releaseId, action, { expectedRevision: release.revision, digest: release.digest, reviewDigest: release.digest }, signal)); if (value && typeof value === "object" && "packageReleaseId" in value) publish({ selectedRelease: value as ReleaseView }); return value; }
  async function install(releaseId = state.selectedRelease?.packageReleaseId) { if (!releaseId || !state.selectedRelease || state.selectedRelease.reviewState !== "APPROVED") throw { code: "STATE_CONFLICT", message: "Install requires an approved selected release." }; const value = await mutate(signal => deps.api.installRelease(releaseId, { dependencyReleaseIds: [] }, signal)); if (value && typeof value === "object" && Array.isArray((value as Record<string, unknown>).packages) && (value as { packages: unknown[] }).packages.some(item => typeof item === "object" && item !== null && (item as Record<string, unknown>).packageReleaseId === releaseId)) { const next = { ...state.selectedRelease, installationState: "INSTALLED" as const }; publish({ selectedRelease: next, releases: state.releases.map(item => item.packageReleaseId === releaseId ? next : item), lastGoodReleases: state.lastGoodReleases.map(item => item.packageReleaseId === releaseId ? next : item) }); } }
  async function grant(input: { releaseId?: string; humanId?: string; revoke?: boolean }) {
    const release = state.selectedRelease;
    const releaseId = input.releaseId ?? release?.packageReleaseId;
    if (!releaseId || !release) return;
    const subject = input.humanId ? { kind: "HUMAN" as const, humanId: input.humanId } : { kind: "ORGANIZATION" as const };
    const current = state.grants.find(item => item.releaseId === releaseId && item.subject.kind === subject.kind && (subject.kind === "ORGANIZATION" || (item.subject.kind === "HUMAN" && item.subject.humanId === subject.humanId)));
    if (input.revoke && (!current || current.revokedAt !== null)) throw conflict("Only a current matching grant can be revoked.");
    if (!input.revoke && current?.revokedAt === null) throw conflict("This exact subject already has a current grant.");
    const expectedRevision = input.revoke ? current!.revision : current?.revision ?? 0;
    const value = await mutate(signal => input.humanId
      ? input.revoke ? deps.api.revokeHuman(releaseId, input.humanId, { expectedRevision }, signal) : deps.api.grantHuman(releaseId, input.humanId, { expectedRevision }, signal)
      : input.revoke ? deps.api.revokeOrganization(releaseId, { expectedRevision }, signal) : deps.api.grantOrganization(releaseId, { expectedRevision }, signal));
    if (value && typeof value === "object" && "grantId" in value) {
      const next = value as GrantView;
      publish({ grants: [...state.grants.filter(item => item.grantId !== next.grantId), next] });
    }
    return value;
  }
  function assertConfirmation(action: ApiExecutionConfirmation["action"], confirmation: ApiExecutionConfirmation) { const release = state.selectedRelease; if (!release || confirmation.action !== action || confirmation.releaseId !== release.packageReleaseId || confirmation.digest !== release.digest || confirmation.acknowledged !== true) { throw { code: "STATE_CONFLICT", message: "Confirmation does not match the selected immutable release and action." }; } const activation = release.apiActivation; if (action === "APPROVE" && activation.approvalState !== "AWAITING_APPROVAL") throw { code: "STATE_CONFLICT", message: "API execution is not awaiting approval." }; if (action === "ACTIVATE" && (activation.approvalState !== "APPROVED" || !["INACTIVE", "FAILED"].includes(activation.runtimeState))) throw { code: "STATE_CONFLICT", message: "API execution cannot be activated in its current state." }; if (action === "DEACTIVATE" && activation.runtimeState !== "ACTIVE") throw { code: "STATE_CONFLICT", message: "API execution is not active." }; }
  function applyActivation(value: ApiActivationResult | undefined) { if (!value || !state.selectedRelease || value.releaseId !== state.selectedRelease.packageReleaseId) return value; publish({ selectedRelease: { ...state.selectedRelease, apiActivation: value } }); return value; }
  async function approveApiExecution(input: ApiExecutionApprovalCommand, confirmation: ApiExecutionConfirmation) { assertConfirmation("APPROVE", confirmation); if (input.releaseId !== confirmation.releaseId || input.digest !== confirmation.digest) throw { code: "STATE_CONFLICT", message: "Approval command does not match the selected immutable digest." }; return applyActivation(await mutate(signal => deps.api.approveApiExecution(input, signal))); }
  async function activateApiExecution(input: ApiExecutionActivationCommand, confirmation: ApiExecutionConfirmation) { assertConfirmation("ACTIVATE", confirmation); if (input.releaseId !== confirmation.releaseId) throw { code: "STATE_CONFLICT", message: "Activation command does not match the selected release." }; return applyActivation(await mutate(signal => deps.api.activateApiExecution(input, signal))); }
  async function deactivateApiExecution(input: ApiExecutionDeactivationCommand, confirmation: ApiExecutionConfirmation) { assertConfirmation("DEACTIVATE", confirmation); if (input.releaseId !== confirmation.releaseId) throw { code: "STATE_CONFLICT", message: "Deactivation command does not match the selected release." }; return applyActivation(await mutate(signal => deps.api.deactivateApiExecution(input, signal))); }
  async function planRollout(input: ActivationPlanCommand) { if (input.agentIds.length === 0 || input.agentIds.length > 256 || new Set(input.agentIds).size !== input.agentIds.length || input.agentIds.some(id => !id) || (input.operation === "SET_PRELOAD" && typeof input.preload !== "boolean") || (input.operation !== "SET_PRELOAD" && input.preload !== undefined)) throw { code: "INVALID_REQUEST", message: "Rollout targets and operation are invalid." }; const value = await mutate(signal => deps.api.planRollout(input, signal)); if (value && typeof value === "object") publish({ rolloutPlan: value as ActivationPlan }); return value; }
  async function confirmRollout(input: { planDigest: string; agentIds: string[] }) { const plan = state.rolloutPlan; if (!plan || input.planDigest !== plan.planDigest || input.agentIds.length !== plan.targets.length || input.agentIds.some((id, index) => id !== plan.targets[index]?.agentId)) throw conflict("Rollout confirmation must match the immutable plan targets and digest."); const value = await mutate(signal => deps.api.confirmRollout(input, signal)); if (value && typeof value === "object") publish({ rollout: value as RolloutView }); return value; }
  async function getRollout(rolloutId: string) { const op = begin(); if (!await authorize(op.principal)) return; const result = await deps.api.getRollout(rolloutId, op.abort.signal); if (!owned(op.generation, op.principal)) return; if (!result.ok) { publish({ busy: false, error: result.error, message: result.error.message }); return; } publish({ busy: false, rollout: result.value, error: null }); return result.value; }
  async function cancelRollout(input: { rolloutId: string; expectedRevision: number }) { const value = await mutate(signal => deps.api.cancelRollout(input, signal)); if (value && typeof value === "object" && "rollout" in value) publish({ rollout: (value as { rollout: RolloutView }).rollout }); return value; }
  async function retry(input: { rolloutId: string; expectedRevision: number }) { if (!state.rollout || state.rollout.id !== input.rolloutId || !["FAILED", "PARTIAL", "CANCELLED"].includes(state.rollout.state)) throw conflict("Only failed or partial rollouts can be retried."); const value = await mutate(signal => deps.api.retryRollout(input, signal)); if (value && typeof value === "object" && "rollout" in value) publish({ rollout: (value as { rollout: RolloutView }).rollout }); return value; }
  async function putCredential(sourceId: string, input: { expectedRevision: number }) {
    if (closed || state.writesBlocked) return;
    const op = begin();
    if (!await authorize(op.principal)) return;
    // Keep this sequence synchronous: no credential copy can occur before authorization,
    // and the draft is gone before the request promise can settle.
    const draft = { username: state.credentialDraft.username, password: state.credentialDraft.password };
    state = { ...state, credentialDraft: { username: "", password: "" } };
    (deps.flushSensitiveUpdate ?? ((notify: () => void) => notify()))(() => listeners.forEach(listener => listener()));
    const result = await deps.api.putReadCredential(sourceId, { ...input, kind: "https-basic", username: draft.username, password: draft.password }, op.abort.signal);
    if (!owned(op.generation, op.principal)) return;
    const liveAuth = await deps.refreshAuth().catch(() => null);
    if (!owned(op.generation, op.principal) || !liveAuth || !liveAuth.authenticated || !liveAuth.isAdmin || liveAuth.mustChangePassword || liveAuth.userId !== deps.expectedUserId) {
      if (owned(op.generation, op.principal)) { principalGeneration += 1; supersede(); publish({ phase: "forbidden", busy: false, credentialDraft: { username: "", password: "" }, selectedSource: null, selectedRelease: null, error: { code: "FORBIDDEN", message: "Administrator access is required." } }); deps.invalidateAuthority(); }
      return;
    }
    if (!result.ok) { publish({ busy: false, error: result.error, message: result.error.message, writesBlocked: result.error.code === "REVISION_CONFLICT" }); return; }
    projectMutation(result.value); publish({ busy: false, message: null, error: null });
    return result.value;
  }
  return { snapshot: () => state, getSnapshot: () => state, subscribe(listener: () => void) { listeners.add(listener); return () => listeners.delete(listener); }, load, restoreUrlSelection, createSource, patchSource, removeSource, restoreSource, deleteCredential, selectSource, selectRelease, selectTab, sync, approve, install, grant, approveApiExecution, activateApiExecution, deactivateApiExecution, planRollout, confirmRollout, getRollout, cancelRollout, retry, setAddDrawerOpen(open: boolean) { if (!closed) publish({ addDrawerOpen: open }); }, setCredentialDraft(draft: Partial<CredentialDraft>) { if (!closed) publish({ credentialDraft: { ...state.credentialDraft, ...draft } }); }, putCredential, dispose() { if (closed) return; closed = true; supersede(); state = { ...state, credentialDraft: { username: "", password: "" }, selectedSource: null, selectedRelease: null, selectedSourceId: null, selectedReleaseId: null, grants: [] }; listeners.clear(); } };
}
